### PR TITLE
Replace deprecated APIs

### PR DESCRIPTION
**Pull request by has207**
Relevant to issue 529 on the pianobar repo.

I tested it as far as building and linking with pianobar, which seemed to work well enough, but I really haven't put in the effort to vet it properly as I'm not at all familiar with the codebase.

### CODE REVIEW

**Comment by PromyLOPh** [comment]
Does it run and play audio? Do the LDFLAGS in Makefile.am need to be
updated?

**Comment by has207** [comment]
pianobar runs and plays audio (and doesn't output the deprecation message). I don't believe any LDFLAGS need updates, it builds fine as is.

**Comment by has207** [comment]
Oh I see what you're asking about with Makefile.am. I actually couldn't get this version you have here to build at all after trying various combinations of automake/autoconf/configure. The patch builds with libao-1.2.0 available from their site and it applied cleanly to this as I think they're only different in all the build support files. It shouldn't need any include or linker changes though so I don't think you need to update any build related files.

Why is this actually different from the source they distribute?

**Comment by PromyLOPh** [comment]
> I actually couldn't get this version you have here to build at all
> after trying various combinations of automake/autoconf/configure. 
Works fine on Linux with ./autogen.sh (ignoring a few deprecation
warnings). Any error messages?

> I think they're only different in all the build support files.
That is correct.

> It shouldn't need any include or linker changes though so I don't
> think you need to update any build related files.
Alright, I’ll merge it.

> Why is this actually different from the source they distribute?
One can build it without installing all the autotools I think.
Essentially they ran ./autogen.sh for you.

**Comment by PromyLOPh** [comment]
FYI: The change has been merged by upstream, see
https://git.xiph.org/?p=libao.git;a=summary

**Pull request merged**
